development: &DEV
  name: events
  stringify: true
  settings:
    index:
      number_of_shards: 4
      number_of_replicas: 1
  mappings:
    event:
      _source:
        includes: ["*"]

test:
  <<: *DEV
  name: events_test
