development: &DEV
  stringify: false
  log_level: 2 # warning
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 1
      refresh_interval: '5s'
  mappings:
    event:
      _source:
        includes: ["*"]

test:
  <<: *DEV
