development: &DEV
  name: search
  stringify: false
  settings:
    index:
      number_of_shards: 4
  mappings:
    event:
      _source:
        includes: ["*"]

test:
  <<: *DEV
  name: search_test
