development: &DEV
  timeout: 2
  retries: 5
  reload_on_failure: true
  extra_falsy_config: false
  servers:
    server1:
      host: localhost
      port: 9200
      protocol: http
    server2:
      host: 127.0.0.1
      port: 9200
      protocol: http

test:
  <<: *DEV
