development: &DEV
  name: events
  permissions:
    create: false
    delete: false
    destroy: false
    read: false
    write: false
  stringify: true
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 1
  mappings:
    event:
      _source:
        includes: ["*"]

test:
  <<: *DEV
  name: events_test
