development: &DEV
  stringify: false
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 1
  mappings:
    geo:
      _source:
        includes: ["*"]
      properties:
        work_area:
          type: geo_shape
          tree: geohash
          precision: 5m

test:
  <<: *DEV
